# -*- coding: utf-8 -*-
"""fatura.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PsfnpFTcorHQuc2zAFCxA40pcrNCV7uQ
"""

def calcular_fatura(demanda, geracao, tarifas):
    faturas_em_reais = []

    for ano in range(len(demanda)):
        diferenca = demanda[ano] - geracao[ano]
        fatura_ano_kwh = max(diferenca, 100)  # A fatura mínima é de 100 kWh
        fatura_ano_reais = fatura_ano_kwh * tarifas[ano]

        faturas_em_reais.append(fatura_ano_reais)

    return faturas_em_reais